version: '3.9'
services:
  fastapi-db:
    image: postgres:15-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - fastapi-data:/var/lib/postgres/data/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - fastapi-db
  fastapi:
    build: ./fastapi
    ports:
      - 3000:5000
    depends_on:
      - fastapi-db
    volumes:
      - ./fastapi/app:/var/lib/fastapi
    restart: always
volumes:
  fastapi-data:

    
